### ISSUE TITLE
Password support

### ISSUE THREAD

**Issue by kamronbatman** [dayvson/go-leaderboard#1]
Thank you so much for your library!
I tried using it with a password protected cloud redis, but it looks like this library doesn't support passwords.  Would it be possible to add that in?

**Comment by dayvson** [comment]
Hey @kamronbatman 
I just added support to password and did a small refactor on how you use the library. 

Take a look and let me know what you think.

**Comment by kamronbatman** [comment]
It looks good, thanks!!
